# Metadata
site_name: Dragon RP
site_description: "The site that will help kickstart your role-play"
site_author: "Dragon Projects"

# Theming
theme:
  name: "material"
  favicon: assets/favicon.ico
  palette:
    primary: "red"
    accent: "red"
  font:
    text: "Ubuntu"
    code: "Ubuntu Mono"
  logo:
    icon: "book"

# Extensions
markdown_extensions:
  - admonition
  - footnotes

# Import
extra_css:
  - "assets/style.css"
extra_javascript:
  - "assets/script.js"

# Repository
repo_url: "https://github.com/jelle619/dragonrp"
edit_uri: "edit/master/docs/"

# Copyright
copyright: "Proudly licensed under CC BY-NC-SA 4.0 by Dragon Projects"
